### ISSUE TITLE
BQuesting-"Ride or Die" Visibility

### ISSUE THREAD

**Issue by Vivrik** [tribesthatmaybe/modpack#42]
The visibility property for the "Ride or Die" quest line can be changed to hide the quest line, but the change doesn't persist between running `bq_admin default save <name>` and `bq_admin default load <name>` .

Tested and reproduceable with both aux bq_admin files and default.

Relogging did not solve the issue.
Restarting client doesn't seem to be a likely fix, but is currently untested.

No noticeable issues in logs via otakup0pe.

Potential bug within bq mod script.

**Comment by otakup0pe** [comment]
Pretty sure the issue is that the hell station quest has no dependencies so it will always be showing as unlocked. I've fixed it by moving that quest to the BRD questline (along with the other east egg / quest line opening things) and am testing now.

[this](https://github.com/Funwayguy/BetterQuesting/wiki/Visibility-and-Logic) wiki page is hella useful.

**Comment by otakup0pe** [comment]
considering this closed i guess
